services:
  app:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    container_name: myanili_app
    ports:
      - 4280:80
      - 4200:4200
    volumes: 
      - ./backend:/app
      - ./frontend:/frontend
    dns:
      - 8.8.8.8
