services:
  app:
    build: .
    container_name: myanili_app
    # depends_on: 
    #   - jikan
    ports:
      - 4280:80
      - 4200:4200
    volumes: 
      - ./backend:/app
      - ./frontend:/frontend
  # jikan:
  #   build:
  #     context: jikan
  #     dockerfile: Dockerfile
  #   container_name: myanili_jikan
  #   depends_on:
  #     - jikan-redis
  #   ports:
  #     - "9001:8000"
  #   networks:
  #     - default

  # jikan-redis:
  #   image: redis
  #   container_name: myanili_redis
