services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: myanili_app
    ports:
      - 4280:80
      - 4200:4200
    volumes:
      - ./backend:/app
      - ./frontend:/frontend
    dns:
      - 8.8.8.8

  jikan:
    image: jikanme/jikan-rest:latest
    ports:
      - 9001:8080
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      LOG_LEVEL: info
      DB_CONNECTION: mongodb
      DB_HOST: jikan-mongodb
      DB_PORT: 27017
      DB_DATABASE: jikan
      DB_USERNAME: jikan
      DB_PASSWORD: jikan_password
      CACHING: "true"
      CACHE_DRIVER: redis
      REDIS_HOST: jikan-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: jikan_redis_password
      MICROCACHING: "true"
      MICROCACHING_EXPIRE: 60
      CORS_MIDDLEWARE: "true"
      SCOUT_DRIVER: typesense
      TYPESENSE_HOST: jikan-typesense
      TYPESENSE_PORT: 8108
      TYPESENSE_API_KEY: jikan_typesense_key
    depends_on:
      jikan-mongodb:
        condition: service_healthy
      jikan-redis:
        condition: service_healthy
      jikan-typesense:
        condition: service_started

  jikan-mongodb:
    image: mongo:focal
    volumes:
      - jikan-mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: jikan_admin
      MONGO_INITDB_ROOT_PASSWORD: jikan_admin_password
      MONGO_INITDB_DATABASE: jikan_admin
    command: "--wiredTigerCacheSizeGB 0.5"
    healthcheck:
      test: ['CMD-SHELL', 'mongosh mongodb://localhost:27017 --quiet --eval "db.runCommand(\"ping\").ok"']
      interval: 30s
      timeout: 10s
      retries: 5

  jikan-redis:
    image: redis:6-alpine
    command: redis-server --requirepass jikan_redis_password
    volumes:
      - jikan-redis-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli -a jikan_redis_password ping | grep -q PONG']
      interval: 5s
      timeout: 2s

  jikan-typesense:
    image: typesense/typesense:0.24.1
    environment:
      TYPESENSE_API_KEY: jikan_typesense_key
      TYPESENSE_DATA_DIR: /data
    volumes:
      - jikan-typesense-data:/data

volumes:
  jikan-mongo-data: {}
  jikan-redis-data: {}
  jikan-typesense-data: {}
