const DeleteUser = {"formData":{"type":"object","properties":{"password":{"type":"string","description":"The user's password"}},"required":["password"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnime = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["cast","characters","related-shows","related-games","related-literatures","seasons","songs","staff","studios"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeCast = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeCharacters = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeRelatedGames = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeRelatedLiteratures = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeRelatedShows = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeStaff = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeStudios = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetAnimeUpcoming = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetCast = {"metadata":{"allOf":[{"type":"object","properties":{"castID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the cast."}},"required":["castID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetCharactersAnime = {"metadata":{"allOf":[{"type":"object","properties":{"characterID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the character."}},"required":["characterID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetCharactersDetails = {"metadata":{"allOf":[{"type":"object","properties":{"characterID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the character."}},"required":["characterID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["people","shows","games","literatures"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetCharactersPeople = {"metadata":{"allOf":[{"type":"object","properties":{"characterID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the character."}},"required":["characterID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetEpisodesDetails = {"metadata":{"allOf":[{"type":"object","properties":{"episodeID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the episode."}},"required":["episodeID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["show","season"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetExplore = {"metadata":{"allOf":[{"type":"object","properties":{"genre_id":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the genre to filter on."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetExploreDetails = {"metadata":{"allOf":[{"type":"object","properties":{"exploreCategoryID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the explore category."}},"required":["exploreCategoryID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetFeedExplore = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetFeedHome = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetFeedMessagesDetails = {"metadata":{"allOf":[{"type":"object","properties":{"messageID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the message."}},"required":["messageID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetFeedMessagesReplies = {"metadata":{"allOf":[{"type":"object","properties":{"messageID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the message."}},"required":["messageID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGame = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["cast","characters","related-shows","related-games","related-literatures","songs","staff","studios"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameCast = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameCharacters = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameRelatedGames = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameRelatedLiteratures = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameRelatedShows = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameStaff = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameStudios = {"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGameUpcoming = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGenreDetails = {"metadata":{"allOf":[{"type":"object","properties":{"genreID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the genre."}},"required":["genreID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetGenres = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetInfo = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetManga = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["cast","characters","related-shows","related-games","related-literatures","staff","studios"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaCast = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaCharacters = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaRelatedGames = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaRelatedLiteratures = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaRelatedShows = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaStaff = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaStudios = {"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMangaUpcoming = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMe = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeAccessTokens = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeAccessTokensAccessToken = {"metadata":{"allOf":[{"type":"object","properties":{"accessToken":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"The access token whose details to retrieve."}},"required":["accessToken"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeFavorites = {"metadata":{"allOf":[{"type":"object","properties":{"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The kind of favorite items to retrieve.","$schema":"http://json-schema.org/draft-04/schema#"},"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":["library"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeFeedMessages = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeFollowers = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeFollowing = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeLibrary = {"metadata":{"allOf":[{"type":"object","properties":{"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The kind of library items to retrieve.","$schema":"http://json-schema.org/draft-04/schema#"},"status":{"type":"string","enum":["Watching","Dropped","Planning","Completed","OnHold"],"default":"Watching","description":"The status to retrieve the library items for.","$schema":"http://json-schema.org/draft-04/schema#"},"sort":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Available sorting options:\n- title(asc/desc)\n- age(newest/oldest)\n- rating(worst/best)\n- my-rating(worst/best)"},"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":["library","status"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeNotifications = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeNotificationsDelete = {"metadata":{"allOf":[{"type":"object","properties":{"notificationUUID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"UUID of the notification to be deleted."}},"required":["notificationUUID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeNotificationsDetails = {"metadata":{"allOf":[{"type":"object","properties":{"notificationUUID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"UUID of the notification to be retrieved."}},"required":["notificationUUID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeRecap = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeRecapYear = {"metadata":{"allOf":[{"type":"object","properties":{"year":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Year of the Re:CAP to be retrieved."}},"required":["year"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeReminderAnime = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeReminderAnimeDownload = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeSessions = {"metadata":{"allOf":[{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMeSessionsSession = {"metadata":{"allOf":[{"type":"object","properties":{"sessionID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the session to be retrieved."}},"required":["sessionID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMyAnimeListAnime = {"metadata":{"allOf":[{"type":"object","properties":{"malID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"MyAnimeList ID of the anime."}},"required":["malID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["cast","characters","related-shows","related-games","related-literatures","seasons","songs","staff","studios"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetMyAnimeListManga = {"metadata":{"allOf":[{"type":"object","properties":{"malID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"MyAnimeList ID of the manga."}},"required":["malID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["cast","characters","related-shows","related-games","related-literatures","staff","studios"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetPeopleAnime = {"metadata":{"allOf":[{"type":"object","properties":{"personID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the person."}},"required":["personID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetPeopleCharacters = {"metadata":{"allOf":[{"type":"object","properties":{"personID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the person."}},"required":["personID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetPeopleDetails = {"metadata":{"allOf":[{"type":"object","properties":{"personID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the person."}},"required":["personID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["characters","shows","games","literatures"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetPrivacyPolicy = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetSchedule = {"metadata":{"allOf":[{"type":"object","properties":{"type":{"type":"integer","enum":[0,1,2],"default":0,"description":"The schedule type.","$schema":"http://json-schema.org/draft-04/schema#"},"date":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"Format: Y-m-d\nThe start date of the schedule. Keep empty for current date."}},"required":["type"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetSearch = {"metadata":{"allOf":[{"type":"object","properties":{"scope":{"type":"string","enum":["kurozora","library"],"default":"kurozora","description":"The scope of the search.","$schema":"http://json-schema.org/draft-04/schema#"},"types[]":{"type":"array","items":{"type":"string","enum":["characters","episodes","games","literatures","people","shows","songs","studios","users"]},"default":"shows","description":"The types used to perform the search.","$schema":"http://json-schema.org/draft-04/schema#"},"query":{"type":"string","minimum":1,"examples":["one piece"],"$schema":"http://json-schema.org/draft-04/schema#","description":"The search query."},"limit":{"type":"string","minimum":1,"maximum":25,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 25."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":["scope","types[]","query"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetSeasons = {"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetSeasonsDetails = {"metadata":{"allOf":[{"type":"object","properties":{"seasonID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the season."}},"required":["seasonID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetSeasonsEpisodes = {"metadata":{"allOf":[{"type":"object","properties":{"seasonID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the season."}},"required":["seasonID"]},{"type":"object","properties":{"hide_fillers":{"type":"integer","enum":[0,1],"default":0,"minimum":0,"maximum":1,"description":"Indicates whether filler episodes should be included.\n- 0 = Include fillers\n- 1 = No fillers","$schema":"http://json-schema.org/draft-04/schema#"},"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetStore = {"metadata":{"allOf":[{"type":"object","properties":{"type":{"type":"integer","enum":[0,1,2,3],"description":"The type of products to fetch.\n- 0: Consumable\n- 1: Non-Consumable\n- 2: Non-Renewing Subscription\n- 3: Auto-Renewing Subscription","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetStudiosAnime = {"metadata":{"allOf":[{"type":"object","properties":{"studioID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the studio."}},"required":["studioID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetStudiosDetails = {"metadata":{"allOf":[{"type":"object","properties":{"studioID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the studio."}},"required":["studioID"]},{"type":"object","properties":{"include[]":{"type":"array","items":{"type":"string","enum":["shows","games","literatures"]},"description":"The relations to include in the response.","$schema":"http://json-schema.org/draft-04/schema#"}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetTermsOfUse = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetThemeDetails = {"metadata":{"allOf":[{"type":"object","properties":{"themeID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the theme."}},"required":["themeID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetThemeStore = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetThemeStoreDetails = {"metadata":{"allOf":[{"type":"object","properties":{"themeID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the theme store item."}},"required":["themeID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetThemes = {"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetUsersFavorites = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]},{"type":"object","properties":{"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The kind of favorite items to retrieve.","$schema":"http://json-schema.org/draft-04/schema#"},"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":["library"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetUsersFeedMessages = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetUsersFollowers = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetUsersFollowing = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]},{"type":"object","properties":{"limit":{"type":"string","minimum":1,"maximum":100,"examples":[25],"$schema":"http://json-schema.org/draft-04/schema#","description":"The limit on the number of objects, or number of objects in the specified relationship, that are returned. The default value is 25 and the maximum value is 100."},"page":{"type":"string","minimum":1,"$schema":"http://json-schema.org/draft-04/schema#","description":"The next page or group of objects to fetch. The default value is 1."}},"required":[]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const GetUsersProfile = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostAnimeRate = {"formData":{"type":"object","properties":{"rating":{"type":"number","format":"double","description":"The rating to leave.","minimum":0,"maximum":5,"examples":[2.5]},"description":{"type":"string","description":"The description accompanying the rating."}},"required":["rating"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"animeID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the anime."}},"required":["animeID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostEpisodeRate = {"formData":{"type":"object","properties":{"rating":{"type":"number","format":"double","description":"The rating to leave.","minimum":0,"maximum":5,"examples":[2.5]},"description":{"type":"string","description":"The description accompanying the rating."}},"required":["rating"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"episodeID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the episode."}},"required":["episodeID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostEpisodesWatched = {"metadata":{"allOf":[{"type":"object","properties":{"episodeID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the episode."}},"required":["episodeID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostFeed = {"formData":{"type":"object","properties":{"body":{"type":"string","description":"Text in the feed message."},"parent_id":{"type":["integer","null"],"description":"ID of the feed message the user is replying to. Omit if not a reply."},"is_reply":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message is a reply or not. If it's a reply then parent_id cannot be empty.\n- 0 = not reply\n- 1 = reply\n\nDefault: `0`"},"is_reshare":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message is a re-share. If it's a re-share then parent_id cannot be empty.\n- 0 = not re-share\n- 1 = re-share\n\nDefault: `0`"},"is_nsfw":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message contains NSFW material.\n- 0 = no NSFW\n- 1 = NSFW\n\nDefault: `0`"},"is_spoiler":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message contains spoiler material.\n- 0 = no spoiler\n- 1 = spoiler\n\nDefault: `0`"}},"required":["body","is_nsfw","is_spoiler"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostFeedMessagesDelete = {"metadata":{"allOf":[{"type":"object","properties":{"messageID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the message."}},"required":["messageID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostFeedMessagesHeart = {"metadata":{"allOf":[{"type":"object","properties":{"messageID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the message."}},"required":["messageID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostFeedMessagesUpdate = {"formData":{"type":"object","properties":{"body":{"type":"string","description":"Text in the feed message."},"is_nsfw":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message contains NSFW material.\n- 0 = no NSFW\n- 1 = NSFW\n\nDefault: `0`"},"is_spoiler":{"type":"integer","enum":[0,1],"default":0,"description":"Whether the message contains spoiler material.\n- 0 = no spoiler\n- 1 = spoiler\n\nDefault: `0`"}},"required":["body","is_nsfw","is_spoiler"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"messageID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the message."}},"required":["messageID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostGameRate = {"formData":{"type":"object","properties":{"rating":{"type":"number","format":"double","description":"The rating to leave.","minimum":0,"maximum":5,"examples":[2.5]},"description":{"type":"string","description":"The description accompanying the rating."}},"required":["rating"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"gameID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the game."}},"required":["gameID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMangaRate = {"formData":{"type":"object","properties":{"rating":{"type":"number","format":"double","description":"The rating to leave.","minimum":0,"maximum":5,"examples":[2.5]},"description":{"type":"string","description":"The description accompanying the rating."}},"required":["rating"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"mangaID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the manga."}},"required":["mangaID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMe = {"body":{"type":"object","properties":{"username":{"type":"string","description":"The new username to set. Send only if user is allowed to change username."},"biography":{"type":"string","description":"The new biography to set. Send <strong>null</strong> to remove."},"profileImage":{"type":"string","format":"binary","description":"The new user's profile image. Send <strong>null</strong> to remove."},"bannerImage":{"type":"string","format":"binary","description":"The new user's banner image. Send <strong>null</strong> to remove."}},"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeAccessTokenUpdate = {"formData":{"type":"object","properties":{"apn_device_token":{"type":"string","description":"The new APN device token for the access token."}},"required":["apn_device_token"],"$schema":"http://json-schema.org/draft-04/schema#"},"metadata":{"allOf":[{"type":"object","properties":{"accessToken":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the access token to be updated."}},"required":["accessToken"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeAccessTokensDelete = {"metadata":{"allOf":[{"type":"object","properties":{"accessToken":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the access token to be deleted."}},"required":["accessToken"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeFavoriteAnime = {"formData":{"type":"object","properties":{"anime_id":{"type":"integer","description":"The ID of the Anime to add."}},"required":["anime_id"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeLibrary = {"formData":{"type":"object","properties":{"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The set of available library kind types.\n- 0 = anime\n- 1 = manga\n- 2 = game\n\nDefault: `0`"},"model_id":{"type":"string","description":"The ID of the model to add."},"status":{"type":"string","enum":["Watching","Dropped","Planning","Completed","OnHold"],"default":"Watching","description":"The set of available library status types.\n\nDefault: `Watching`"}},"required":["library","model_id","status"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeLibraryDelete = {"formData":{"type":"object","properties":{"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The set of available library kind types.\n- 0 = anime\n- 1 = manga\n- 2 = game\n\nDefault: `0`"},"model_id":{"type":"string","description":"The ID of the model to remove."}},"required":["library","model_id"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeLibraryImport = {"body":{"type":"object","properties":{"file":{"type":"string","format":"binary","description":"The library export file"},"library":{"type":"integer","enum":[0,1,2],"default":0,"description":"The set of available library kind types.\n- 0 = anime\n- 1 = manga\n- 2 = game\n\nDefault: `0`"},"service":{"type":"integer","enum":[0,1],"default":1,"description":"The set of available import service types.\n- 0 = MyAnimeList\n- 1 = Kitsu\n\nDefault: `1`"},"behavior":{"type":"integer","enum":[0,1],"default":1,"description":"The set of available import behavior types.\n- 0 = overwrite\n- 1 = merge\n\nDefault: `1`"}},"required":["file","library","service","behavior"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeNotificationsUpdate = {"formData":{"type":"object","properties":{"notification":{"type":"array","items":{"type":"string"},"minItems":1,"uniqueItems":true,"description":"The UUID of the notification to update. Use \"all\" to update all of the user's notifications."},"read":{"type":"integer","enum":[0,1],"default":1,"description":"The notification read status used to mark a notification as read or unread.\n- 0 = unread\n- 1 = read\n\nDefault: `1`"}},"required":["notification","read"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeReminderAnime = {"formData":{"type":"object","properties":{"anime_id":{"type":"integer","description":"The ID of the Anime to add or remove."}},"required":["anime_id"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostMeSessionsDelete = {"metadata":{"allOf":[{"type":"object","properties":{"sessionID":{"type":"string","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the session to be deleted."}},"required":["sessionID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostResetPassword = {"formData":{"type":"object","properties":{"email":{"type":"string","description":"The email of the user to request a password reset."}},"required":["email"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostSeasonsWatched = {"metadata":{"allOf":[{"type":"object","properties":{"seasonID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the season."}},"required":["seasonID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostSignIn = {"formData":{"type":"object","properties":{"email":{"type":"string","description":"The user's email address"},"password":{"type":"string","description":"The user's password"},"platform":{"type":"string","description":"The platform that was used to create the session","examples":["iOS"]},"platform_version":{"type":"string","description":"The platform version that was used to create the session","examples":["13.4"]},"device_vendor":{"type":"string","description":"The device vendor that was used to create the session","examples":["Apple"]},"device_model":{"type":"string","description":"The device model that was used to create the session","examples":["iPhone 11 Pro Max"]}},"required":["email","password","platform","platform_version","device_vendor","device_model"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostSiwASignIn = {"formData":{"type":"object","properties":{"token":{"type":"string","description":"The identity token (JWT) as provided by Apple"},"platform":{"type":"string","description":"The platform that was used to create the session","examples":["iOS"]},"platform_version":{"type":"string","description":"The platform version that was used to create the session","examples":["13.4"]},"device_vendor":{"type":"string","description":"The device vendor that was used to create the session","examples":["Apple"]},"device_model":{"type":"string","description":"The device model that was used to create the session","examples":["iPhone 11 Pro Max"]}},"required":["token","platform","platform_version","device_vendor","device_model"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostStoreVerify = {"body":{"type":"object","properties":{"receipt":{"type":"string","description":"The Base64 encoded receipt data."}},"required":["receipt"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostUsers = {"body":{"type":"object","properties":{"username":{"type":"string","description":"The new user's username","examples":["Kurozora"]},"password":{"type":"string","description":"The new user's password"},"email":{"type":"string","description":"The new user's email"},"profileImage":{"type":"string","format":"binary","description":"The new user's profile image"}},"required":["username","password","email"],"$schema":"http://json-schema.org/draft-04/schema#"},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
const PostUsersFollow = {"metadata":{"allOf":[{"type":"object","properties":{"userID":{"type":"integer","$schema":"http://json-schema.org/draft-04/schema#","description":"ID of the user."}},"required":["userID"]}]},"response":{"200":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"400":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"},"403":{"type":"object","additionalProperties":true,"$schema":"http://json-schema.org/draft-04/schema#"}}} as const
;
export { DeleteUser, GetAnime, GetAnimeCast, GetAnimeCharacters, GetAnimeRelatedGames, GetAnimeRelatedLiteratures, GetAnimeRelatedShows, GetAnimeStaff, GetAnimeStudios, GetAnimeUpcoming, GetCast, GetCharactersAnime, GetCharactersDetails, GetCharactersPeople, GetEpisodesDetails, GetExplore, GetExploreDetails, GetFeedExplore, GetFeedHome, GetFeedMessagesDetails, GetFeedMessagesReplies, GetGame, GetGameCast, GetGameCharacters, GetGameRelatedGames, GetGameRelatedLiteratures, GetGameRelatedShows, GetGameStaff, GetGameStudios, GetGameUpcoming, GetGenreDetails, GetGenres, GetInfo, GetManga, GetMangaCast, GetMangaCharacters, GetMangaRelatedGames, GetMangaRelatedLiteratures, GetMangaRelatedShows, GetMangaStaff, GetMangaStudios, GetMangaUpcoming, GetMe, GetMeAccessTokens, GetMeAccessTokensAccessToken, GetMeFavorites, GetMeFeedMessages, GetMeFollowers, GetMeFollowing, GetMeLibrary, GetMeNotifications, GetMeNotificationsDelete, GetMeNotificationsDetails, GetMeRecap, GetMeRecapYear, GetMeReminderAnime, GetMeReminderAnimeDownload, GetMeSessions, GetMeSessionsSession, GetMyAnimeListAnime, GetMyAnimeListManga, GetPeopleAnime, GetPeopleCharacters, GetPeopleDetails, GetPrivacyPolicy, GetSchedule, GetSearch, GetSeasons, GetSeasonsDetails, GetSeasonsEpisodes, GetStore, GetStudiosAnime, GetStudiosDetails, GetTermsOfUse, GetThemeDetails, GetThemeStore, GetThemeStoreDetails, GetThemes, GetUsersFavorites, GetUsersFeedMessages, GetUsersFollowers, GetUsersFollowing, GetUsersProfile, PostAnimeRate, PostEpisodeRate, PostEpisodesWatched, PostFeed, PostFeedMessagesDelete, PostFeedMessagesHeart, PostFeedMessagesUpdate, PostGameRate, PostMangaRate, PostMe, PostMeAccessTokenUpdate, PostMeAccessTokensDelete, PostMeFavoriteAnime, PostMeLibrary, PostMeLibraryDelete, PostMeLibraryImport, PostMeNotificationsUpdate, PostMeReminderAnime, PostMeSessionsDelete, PostResetPassword, PostSeasonsWatched, PostSignIn, PostSiwASignIn, PostStoreVerify, PostUsers, PostUsersFollow }
